### ISSUE TITLE
JSON Import via App Extension

### ISSUE THREAD

**Issue by henribredt** [PrivacyAnalyticsApp/PrivacyAnalyticsApp#3]
JSON privacy report log aus der Einstellungen App muss in die App geladen werden können, dazu ist vermutlich eine Share Extension erforderlich

[App Extensions - Apple Developer](https://developer.apple.com/app-extensions/)
[App Extension Programming Guide](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Action.html#//apple_ref/doc/uid/TP40014214-CH13-SW1)
[iOS Share extension - Medium](https://medium.com/macoclock/ios-share-extension-swift-5-1-1606263746b)

**To-Do**
- [x] Share Extension Target hinzufügen, erstmal mit `NSExtensionActivationSupportsFileWithMaxCount` activation rule
- [ ] Geteilte Datei im App Container speichern
- [ ] Activation rule so spezifizieren, dass nur JSON files akzeptiert werden mit SUBQUERY [Documentation](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/AppExtensionKeys.html)

**Comment by henribredt** [comment]
Main app and share extension müssen sich in einer App Group befinden, um Daten austauschen zu können
https://www.atomicbird.com/blog/sharing-with-app-extensions/

**Comment by henribredt** [comment]
Sowohl Share Extension als auch Action Extension sind möglich
